---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Download k3s
  when: k3s_version_output.rc != 0
  block:
    - name: Download install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: Initialize the first k3s master
      when: inventory_hostname == groups['master'][0]
      block:
        - name: Run install script
          ansible.builtin.command:
            cmd: /usr/local/bin/k3s-install.sh
          environment:
            INSTALL_K3S_VERSION: "{{ k3s_version }}"
            INSTALL_K3S_EXEC: "server --cluster-init --tls-san {{ vip }} --disable servicelb --node-ip {{ hostvars[groups['master'][0]]['ansible_host'] }}"
            K3S_TOKEN: "{{ k3s_token }}"
          changed_when: true

        - name: Make directory
          ansible.builtin.file:
            path: /var/lib/rancher/k3s/server/manifests
            state: directory

        - name: Download Kube-VIP RBAC manifest
          ansible.builtin.get_url:
            url: https://kube-vip.io/manifests/rbac.yaml
            dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml

        - name: Pull kube-vip docker image
          ansible.builtin.command:
            cmd: ctr image pull docker.io/plndr/kube-vip:latest            
          changed_when: false

        - name: Generate kube-vip daemonset manifest
          ansible.builtin.shell:
            cmd: >
              ctr run --rm --net-host docker.io/plndr/kube-vip:latest vip /kube-vip
              manifest daemonset
              --interface {{ vip_interface | default('eth0') }}
              --address {{ vip }}
              --inCluster
              --taint
              --controlplane
              --services
              --arp
              --leaderElection
              | tee /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
            creates: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml

        - name: Install kube-vip cloud provider
          ansible.builtin.command:
            cmd: kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml

        - name: Create a global IP range
          ansible.builtin.command:
            cmd: kubectl create configmap -n kube-system kubevip --from-literal range-global={{ vip_range }}

    - name: Join other masters to the cluster
      when: inventory_hostname != groups['master'][0]
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --disable servicelb --node-ip {{ ansible_host }}"
        K3S_TOKEN: "{{ k3s_token }}"
        K3S_URL: "https://{{ vip }}:6443"
      changed_when: true

- name: Setup kubectl for user
  block:
    - name: Create directory .kube
      ansible.builtin.file:
        path: ~{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o="

    - name: Copy config file to user home directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~{{ ansible_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="

    - name: Configure default KUBECONFIG for user
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: 'export KUBECONFIG=~/.kube/config'
        line: 'export KUBECONFIG=~/.kube/config # Added by k3s-ansible'
        state: present

    - name: Configure kubectl autocomplete
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: '\.\s+<\(kubectl completion bash\)'
        line: ". <(kubectl completion bash)  # Added by k3s-ansible"

    - name: Add kube-vip alias
      ansible.builtin.lineinfile:
        path: "~{{ ansible_user }}/.bashrc"
        regexp: 'alias kube-vip='
        line: 'alias kube-vip="sudo ctr run --rm --net-host docker.io/plndr/kube-vip:latest vip /kube-vip"  # Added by k3s-ansible'
        state: present
