---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Download k3s
  when: k3s_version_output.rc != 0
  block:
    - name: Download install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: Download k3s binary
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        # INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server"
        K3S_TOKEN: "{{ k3s_token }}"
      changed_when: true

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Configure default KUBECONFIG for user
  ansible.builtin.lineinfile:
    path: ~{{ ansible_user }}/.bashrc
    regexp: 'export KUBECONFIG=~/.kube/config'
    line: 'export KUBECONFIG=~/.kube/config # Added by k3s-ansible'
    state: present

